export const ADD_USERNAME = "ADD_USERNAME";
export const ADD_TEMP_USERNAME = "ADD_TEMP_USERNAME";
export const RESET_TEMP_USERNAME = "RESET_TEMP_USERNAME";
export const CREATE_RANDOM_QUEUE = "CREATE_RANDOM_QUEUE";
export const CHANGE_ACTIVE_QUESTION_NDX = "CHANGE_ACTIVE_QUESTION_NDX";
